import type { Theme } from './theme.types';

export const tokens: Record<keyof Theme, string> = {
  borderRadiusNone: 'var(--borderRadiusNone)',
  borderRadiusSmall: 'var(--borderRadiusSmall)',
  borderRadiusMedium: 'var(--borderRadiusMedium)',
  borderRadiusLarge: 'var(--borderRadiusLarge)',
  borderRadiusXLarge: 'var(--borderRadiusXLarge)',
  borderRadiusCircular: 'var(--borderRadiusCircular)',
  fontSizeBase100: 'var(--fontSizeBase100)',
  fontSizeBase200: 'var(--fontSizeBase200)',
  fontSizeBase300: 'var(--fontSizeBase300)',
  fontSizeBase400: 'var(--fontSizeBase400)',
  fontSizeBase500: 'var(--fontSizeBase500)',
  fontSizeBase600: 'var(--fontSizeBase600)',
  fontSizeHero700: 'var(--fontSizeHero700)',
  fontSizeHero800: 'var(--fontSizeHero800)',
  fontSizeHero900: 'var(--fontSizeHero900)',
  fontSizeHero1000: 'var(--fontSizeHero1000)',
  lineHeightBase100: 'var(--lineHeightBase100)',
  lineHeightBase200: 'var(--lineHeightBase200)',
  lineHeightBase300: 'var(--lineHeightBase300)',
  lineHeightBase400: 'var(--lineHeightBase400)',
  lineHeightBase500: 'var(--lineHeightBase500)',
  lineHeightBase600: 'var(--lineHeightBase600)',
  lineHeightHero700: 'var(--lineHeightHero700)',
  lineHeightHero800: 'var(--lineHeightHero800)',
  lineHeightHero900: 'var(--lineHeightHero900)',
  lineHeightHero1000: 'var(--lineHeightHero1000)',
  fontFamily: 'var(--fontFamily)',
  fontFamilyMono: 'var(--fontFamilyMono)',
  fontFamilySpicy: 'var(--fontFamilySpicy)',
  fontWeightRegular: 'var(--fontWeightRegular)',
  fontWeightMedium: 'var(--fontWeightMedium)',
  fontWeightSemibold: 'var(--fontWeightSemibold)',
  strokeWidthThin: 'var(--strokeWidthThin)',
  strokeWidthThick: 'var(--strokeWidthThick)',
  strokeWidthThicker: 'var(--strokeWidthThicker)',
  strokeWidthThickest: 'var(--strokeWidthThickest)',
  spacingHorizontalNone: 'var(--spacingHorizontalNone)',
  spacingHorizontalXXS: 'var(--spacingHorizontalXXS)',
  spacingHorizontalXS: 'var(--spacingHorizontalXS)',
  spacingHorizontalSNudge: 'var(--spacingHorizontalSNudge)',
  spacingHorizontalS: 'var(--spacingHorizontalS)',
  spacingHorizontalMNudge: 'var(--spacingHorizontalMNudge)',
  spacingHorizontalM: 'var(--spacingHorizontalM)',
  spacingHorizontalL: 'var(--spacingHorizontalL)',
  spacingHorizontalXL: 'var(--spacingHorizontalXL)',
  spacingHorizontalXXL: 'var(--spacingHorizontalXXL)',
  spacingHorizontalXXXL: 'var(--spacingHorizontalXXXL)',
  spacingVerticalNone: 'var(--spacingVerticalNone)',
  spacingVerticalXXS: 'var(--spacingVerticalXXS)',
  spacingVerticalXS: 'var(--spacingVerticalXS)',
  spacingVerticalSNudge: 'var(--spacingVerticalSNudge)',
  spacingVerticalS: 'var(--spacingVerticalS)',
  spacingVerticalMNudge: 'var(--spacingVerticalMNudge)',
  spacingVerticalM: 'var(--spacingVerticalM)',
  spacingVerticalL: 'var(--spacingVerticalL)',
  spacingVerticalXL: 'var(--spacingVerticalXL)',
  spacingVerticalXXL: 'var(--spacingVerticalXXL)',
  spacingVerticalXXXL: 'var(--spacingVerticalXXXL)',
  // durationUltraFast: 'var(--durationUltraFast)',
  // durationFaster: 'var(--durationFaster)',
  // durationFast: 'var(--durationFast)',
  // durationNormal: 'var(--durationNormal)',
  // durationSlow: 'var(--durationSlow)',
  // durationSlower: 'var(--durationSlower)',
  // durationUltraSlow: 'var(--durationUltraSlow)',
  bg1: 'var(--bg1)',
  bg2: 'var(--bg2)',
  bg3: 'var(--bg3)',
  bg4: 'var(--bg4)',
  bgTransparent: 'var(--bgTransparent)',
  bgDisable: 'var(--bgDisable)',
  bgNote: 'var(--bgNote)',
  bgImportant: 'var(--bgImportant)',
  bgTip: 'var(--bgTip)',
  bgCaution: 'var(--bgCaution)',
  bgWarning: 'var(--bgWarning)',
  f1: 'var(--f1)',
  f2: 'var(--f2)',
  f3: 'var(--f3)',
  f4: 'var(--f4)',
  f5: 'var(--f5)',
  f6: 'var(--f6)',
  f7: 'var(--f7)',
  f8: 'var(--f8)',
  f9: 'var(--f9)',
  f10: 'var(--f10)',
  fDisable: 'var(--fDisable)',
  b1: 'var(--b1)',
  b2: 'var(--b2)',
  bNote: 'var(--bNote)',
  bImportant: 'var(--bImportant)',
  bTip: 'var(--bTip)',
  bCaution: 'var(--bCaution)',
  bWarning: 'var(--bWarning)',
  bDisable: 'var(--bDisable)',
  syntaxBg: 'var(--syntaxBg)',
  syntaxHighlight: 'var(--syntaxHighlight)',
  syntaxTxt: 'var(--syntaxTxt)',
  syntaxComment: 'var(--syntaxComment)',
  syntaxProp: 'var(--syntaxProp)',
  syntaxBool: 'var(--syntaxBool)',
  syntaxVal: 'var(--syntaxVal)',
  syntaxStr: 'var(--syntaxStr)',
  syntaxName: 'var(--syntaxName)',
  syntaxDel: 'var(--syntaxDel)',
  syntaxRegex: 'var(--syntaxRegex)',
  syntaxFn: 'var(--syntaxFn)',
  h1: 'var(--h1)',
  h2: 'var(--h2)',
  h3: 'var(--h3)',
  h4: 'var(--h4)',
  h5: 'var(--h5)',
  spColorsFgActive: 'var(--spColorsFgActive)',
  spColorsFgDefault: 'var(--spColorsFgDefault)',
  spColorsFgInactive: 'var(--spColorsFgInactive)',
  spColorsBgActive: 'var(--spColorsBgActive)',
  spColorsBgDefault: 'var(--spColorsBgDefault)',
  spColorsBgDefaultOverlay: 'var(--spColorsBgDefaultOverlay)',
  spColorsBgInput: 'var(--spColorsBgInput)',
  spColorsAccent: 'var(--spColorsAccent)',
  spColorsBgError: 'var(--spColorsBgError)',
  spColorsFgError: 'var(--spColorsFgError)',
  themePlain: 'var(--themePlain)',
  themeComment: 'var(--themeComment)',
  themeKeyword: 'var(--themeKeyword)',
  themeTag: 'var(--themeTag)',
  themePunctuation: 'var(--themePunctuation)',
  themeDefinition: 'var(--themeDefinition)',
  themeProperty: 'var(--themeProperty)',
  themeStatic: 'var(--themeStatic)',
  themeString: 'var(--themeString)',
  bg5: 'var(--bg5)',
  bg6: 'var(--bg6)',
  bg7: 'var(--bg7)',
  bg8: 'var(--bg8)',
  bg9: '',
  bg10: '',

  //

  shadow16: 'var(--shadow16)',
};
